global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
  - job_name: 'monitor'
    honor_timestamps: true
    scrape_interval: 2s
    scrape_timeout: 2s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - monitor:52323